#!/bin/sh
#
# Quick and dirty script to update the sidebars for the gnustep web site
#
files=`grep -l aboutGNUstep */*html */*php`
#afiles=`grep -l aboutGNUstep */*/*html`

for f in $files; do
  echo updating $f
  scripts/retemplate $f > tempit;
  mv tempit $f;
done
