#!/usr/bin/perl
eval 'exec /usr/bin/perl -S $0 ${1+"$@"}'
    if $running_under_some_shell;
			# this emulates #! processing on NIH machines.
			# (remove #! line above if indigestible)

eval '$'.$1.'$2;' while $ARGV[0] =~ /^([A-Za-z_0-9]+=)(.*)/ && shift;
			# process any FOO=bar switches

$[ = 1;			# set array base to 1
$, = ' ';		# set output field separator
$\ = "\n";		# set output record separator

  #open(TMPL,"<$ENV{'GNUSTEP_WEB_ROOT'}/secondary.html.template");
  open(TMPL,"secondary.html.template");
  $tmpl=join("",<TMPL>);
  close(TMPL);
  ($T2H_EXTRA_HEAD,$T2H_AFTER_BODY_OPEN,$T2H_PRE_BODY_CLOSE) =
    ($tmpl=~/<\/title>(.*)<\/head>.*<body>(.*<div id="main">).*(<\/div><\/div>.*)<\/body>/sm);

$lasttol = '';
$sim = 0;
while (<>) {
    chomp;	# strip record separator
    @Fld = split(' ', $_, 9999);

    if (substr($Fld[1], 1, 6) eq '</div>') {
	$sim = $sim + 1;	
      }
    elsif (substr($Fld[1], 1, 7) eq '</body>') {
	$sim = 0;
      }

    if ($sim == 1) {
      printf "%s", $T2H_PRE_BODY_CLOSE;
      $sim = $sim + 1;
      }
    elsif ($sim < 2) {
      print $_;
      }

}
